# Generated by Django 5.2.16 on 2026-08-22 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paystack_reference",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount in KES", max_digits=12
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("card", "Card"),
                            ("mobile_money", "Mobile Money (M-Pesa)"),
                            ("bank_transfer", "Bank Transfer"),
                            ("ussd", "USSD"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "paystack_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw Paystack webhook/verify payload for audit trail",
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "dfa_payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
