# Generated by Django 5.2.16 on 2026-08-22 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FulfillmentOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("printful", "Printful"), ("printify", "Printify")],
                        max_length=20,
                    ),
                ),
                (
                    "external_order_id",
                    models.CharField(
                        blank=True,
                        help_text="Order ID returned by Printful or Printify",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted to Provider"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("tracking_number", models.CharField(blank=True, max_length=200)),
                ("tracking_url", models.URLField(blank=True, max_length=500)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_delivery", models.DateField(blank=True, null=True)),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw provider API response for debugging",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fulfillment_order",
                        to="orders.orderitem",
                    ),
                ),
            ],
            options={
                "db_table": "dfa_fulfillment_orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
