# Generated by Django 5.2.16 on 2026-08-22 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("digital", "Digital Download"),
                            ("physical", "Physical Product"),
                            ("limited", "Limited Edition"),
                            ("license", "Commercial License"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in KES (Paystack charges in smallest unit × 100)",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="gallery.artwork",
                    ),
                ),
            ],
            options={
                "db_table": "dfa_products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhysicalProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fulfillment_provider",
                    models.CharField(
                        choices=[("printful", "Printful"), ("printify", "Printify")],
                        default="printful",
                        max_length=20,
                    ),
                ),
                ("printful_product_id", models.CharField(blank=True, max_length=100)),
                ("printify_product_id", models.CharField(blank=True, max_length=100)),
                (
                    "weight_grams",
                    models.PositiveIntegerField(
                        default=0, help_text="Approximate weight for shipping estimates"
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="physical_detail",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "db_table": "dfa_physical_products",
            },
        ),
        migrations.CreateModel(
            name="LimitedEdition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "edition_size",
                    models.PositiveSmallIntegerField(
                        default=25, help_text="Maximum number of copies available"
                    ),
                ),
                (
                    "edition_sold",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number sold so far - auto-incremented on purchase",
                    ),
                ),
                (
                    "includes_original_sketch",
                    models.BooleanField(
                        default=False,
                        help_text="Physical original pencil sketch included",
                    ),
                ),
                (
                    "includes_print",
                    models.BooleanField(
                        default=True, help_text="Signed print included"
                    ),
                ),
                (
                    "includes_digital",
                    models.BooleanField(
                        default=True, help_text="Digital download included"
                    ),
                ),
                (
                    "certificate_text",
                    models.TextField(
                        blank=True, help_text="Certificate of authenticity text"
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limited_detail",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "db_table": "dfa_limited_editions",
            },
        ),
        migrations.CreateModel(
            name="LicenseProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_scope",
                    models.CharField(
                        choices=[
                            ("personal", "Personal Use"),
                            ("commercial", "Commercial Use"),
                            ("exclusive", "Exclusive License"),
                        ],
                        default="commercial",
                        max_length=20,
                    ),
                ),
                (
                    "usage_description",
                    models.TextField(
                        blank=True,
                        help_text="What the licensee is permitted to do with this artwork",
                    ),
                ),
                (
                    "allowed_uses",
                    models.TextField(
                        blank=True, help_text="Bullet-point list of permitted uses"
                    ),
                ),
                (
                    "restrictions",
                    models.TextField(
                        blank=True, help_text="What the licensee may NOT do"
                    ),
                ),
                (
                    "is_exclusive",
                    models.BooleanField(
                        default=False,
                        help_text="If true, no other licenses for this artwork will be sold after purchase",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license_detail",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "db_table": "dfa_license_products",
            },
        ),
        migrations.CreateModel(
            name="DigitalProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_url",
                    models.CharField(
                        help_text="GitHub stored_path for the full-resolution download file. Never exposed directly - only served via signed download URL.",
                        max_length=512,
                    ),
                ),
                ("file_size_bytes", models.PositiveBigIntegerField(default=0)),
                (
                    "file_format",
                    models.CharField(
                        default="PNG",
                        help_text='e.g. "PNG", "PDF", "ZIP"',
                        max_length=20,
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal Use"),
                            ("commercial", "Commercial Use"),
                            ("exclusive", "Exclusive License"),
                        ],
                        default="personal",
                        max_length=20,
                    ),
                ),
                (
                    "includes_description",
                    models.TextField(
                        blank=True,
                        help_text="What the customer receives, shown on the product page",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digital_detail",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "db_table": "dfa_digital_products",
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, help_text='e.g. "S", "M", "XL"', max_length=10
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50)),
                ("printful_variant_id", models.CharField(blank=True, max_length=100)),
                ("printify_variant_id", models.CharField(blank=True, max_length=100)),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank to use base product price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("stock_available", models.BooleanField(default=True)),
                (
                    "physical_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="store.physicalproduct",
                    ),
                ),
            ],
            options={
                "db_table": "dfa_product_variants",
                "ordering": ["size", "color"],
            },
        ),
    ]
