# Generated by Django 5.2.16 on 2026-08-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="physicalproduct",
            name="mockup_image_url",
            field=models.URLField(
                blank=True,
                help_text="Default product mockup image from Printify/Printful",
                max_length=500,
            ),
        ),
    ]
