# Generated by Django 5.2.16 on 2026-08-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_physicalproduct_mockup_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="physicalproduct",
            name="mockup_images",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of all mockup image URLs for different colors and views",
            ),
        ),
    ]
