# Generated by Django 5.2.16 on 2026-08-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_physicalproduct_mockup_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gallery_sort_order",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Lower numbers appear first in the Gallery page featured products section.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="show_in_gallery",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Show this physical product in the Gallery page featured products section.",
            ),
        ),
    ]
