# Generated by Django 5.2.16 on 2026-08-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_product_gallery_sort_order_product_show_in_gallery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="size",
            field=models.CharField(
                blank=True,
                help_text='e.g. "S", "M", "XL", "30 x 40", or "One size"',
                max_length=50,
            ),
        ),
    ]
