# Generated by Django 5.2.16 on 2026-08-28 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_alter_artwork_style"),
        ("store", "0005_alter_productvariant_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="artwork",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="gallery.artwork",
            ),
        ),
    ]
