# Generated by Django 5.2.16 on 2026-08-22 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "story",
                    models.TextField(
                        blank=True,
                        help_text="The artistic story/process behind this piece — shown on the product page",
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("neon_graffiti", "Neon Graffiti"),
                            ("black_red_metal", "Black & Red Metal"),
                            ("cyberpunk", "Cyberpunk"),
                            ("japanese", "Japanese-Inspired"),
                            ("tattoo_flash", "Tattoo Flash"),
                            ("street_art", "Street Art Mural"),
                            ("chrome", "Chrome"),
                            ("gothic", "Gothic"),
                            ("african", "African-Inspired"),
                            ("vintage", "Distressed Vintage"),
                            ("minimal_bw", "Minimal Black & White"),
                            ("original", "Original Pencil"),
                            ("other", "Other"),
                        ],
                        default="neon_graffiti",
                        max_length=30,
                    ),
                ),
                (
                    "artwork_type",
                    models.CharField(
                        choices=[
                            ("original", "Original Drawing"),
                            ("digital", "Digital Artwork"),
                            ("limited", "Limited Edition"),
                            ("merch_design", "Merchandise Design"),
                        ],
                        default="digital",
                        max_length=20,
                    ),
                ),
                (
                    "original_pencil_url",
                    models.CharField(
                        blank=True,
                        help_text="GitHub stored_path for the original pencil sketch",
                        max_length=512,
                    ),
                ),
                (
                    "colored_url",
                    models.CharField(
                        blank=True,
                        help_text="GitHub stored_path for the AI-colored intermediate version",
                        max_length=512,
                    ),
                ),
                (
                    "preview_url",
                    models.CharField(
                        blank=True,
                        help_text="GitHub stored_path for the watermarked low-res preview (shown publicly)",
                        max_length=512,
                    ),
                ),
                (
                    "final_url",
                    models.CharField(
                        blank=True,
                        help_text="GitHub stored_path for the full-resolution final artwork. NEVER exposed in templates — only sent via signed download URL after payment.",
                        max_length=512,
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                (
                    "is_featured",
                    models.BooleanField(default=False, help_text="Show on homepage"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dfa_artworks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArtworkTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                "db_table": "dfa_artwork_tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ArtworkImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        help_text="GitHub stored_path for this step image",
                        max_length=512,
                    ),
                ),
                (
                    "step_label",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Original Sketch", "Graffiti Treatment", "Final Artwork"',
                        max_length=100,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "artwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_images",
                        to="gallery.artwork",
                    ),
                ),
            ],
            options={
                "db_table": "dfa_artwork_images",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="artwork",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="artworks", to="gallery.artworktag"
            ),
        ),
    ]
