# Generated by Django 5.2.16 on 2026-08-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="style",
            field=models.CharField(
                choices=[
                    ("neon_graffiti", "Neon Graffiti"),
                    ("dark_surrealism", "Dark Surrealism"),
                    ("occult", "Occult & Mystic"),
                    ("gothic", "Gothic"),
                    ("black_red_metal", "Black & Red Metal"),
                    ("cyberpunk", "Cyberpunk"),
                    ("street_art", "Street Art Mural"),
                    ("japanese", "Japanese-Inspired"),
                    ("tattoo_flash", "Tattoo Flash"),
                    ("chrome", "Chrome"),
                    ("african", "African-Inspired"),
                    ("vintage", "Distressed Vintage"),
                    ("minimal_bw", "Minimal Black & White"),
                    ("original", "Original Pencil"),
                    ("other", "Other"),
                ],
                default="neon_graffiti",
                max_length=30,
            ),
        ),
    ]
