# Generated by Django 5.2.16 on 2026-08-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.CharField(
                blank=True, help_text="Profile photo image URL", max_length=1024
            ),
        ),
    ]
