# Generated by Django 5.2.16 on 2026-08-22 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("basic", "Basic - Digital artwork"),
                            ("premium", "Premium - Custom + revisions"),
                            ("commercial", "Commercial - Business / brand use"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("reviewing", "Under Review"),
                            ("quoted", "Quoted"),
                            ("deposit_paid", "Deposit Paid"),
                            ("in_progress", "In Progress"),
                            ("preview_sent", "Preview Sent"),
                            ("revision_requested", "Revision Requested"),
                            ("final_payment_due", "Final Payment Due"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='Short title for the artwork, e.g. "Demon Skull with Initials"',
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Full description of what the customer wants"
                    ),
                ),
                (
                    "preferred_style",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Neon Graffiti", "Gothic", "Cyberpunk"',
                        max_length=100,
                    ),
                ),
                (
                    "preferred_colors",
                    models.CharField(
                        blank=True, help_text="Preferred color palette", max_length=200
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "A4 portrait", "2000×2000px", "phone wallpaper"',
                        max_length=100,
                    ),
                ),
                (
                    "intended_use",
                    models.CharField(
                        choices=[
                            ("personal", "Personal (wallpaper, print, etc.)"),
                            ("commercial", "Commercial (merch, brand, album, etc.)"),
                        ],
                        default="personal",
                        max_length=20,
                    ),
                ),
                (
                    "reference_images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of GitHub stored_paths for reference images",
                    ),
                ),
                (
                    "sketch_upload_url",
                    models.CharField(
                        blank=True,
                        help_text="GitHub stored_path for an uploaded sketch",
                        max_length=512,
                    ),
                ),
                (
                    "quoted_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price quoted by the artist (KES)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Deposit required (typically 50% of quoted price)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Remaining balance after deposit",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "final_file_url",
                    models.CharField(
                        blank=True,
                        help_text="GitHub stored_path for the final delivered file - released after final payment",
                        max_length=512,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dfa_commissions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommissionMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "attachment_url",
                    models.CharField(
                        blank=True,
                        help_text="Optional GitHub stored_path for an image attachment",
                        max_length=512,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="commissions.commission",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dfa_commission_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommissionRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision_number", models.PositiveSmallIntegerField(default=1)),
                (
                    "artist_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes from the artist about this revision",
                    ),
                ),
                (
                    "preview_url",
                    models.CharField(
                        blank=True,
                        help_text="GitHub stored_path for watermarked preview image",
                        max_length=512,
                    ),
                ),
                (
                    "client_response",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting Response"),
                            ("approved", "Approved"),
                            ("revision_requested", "Revision Requested"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "client_notes",
                    models.TextField(
                        blank=True, help_text="Feedback from client for this revision"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "commission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="commissions.commission",
                    ),
                ),
            ],
            options={
                "db_table": "dfa_commission_revisions",
                "ordering": ["revision_number"],
            },
        ),
    ]
